### ISSUE TITLE
Par when I go to Message Part .. There is an Error

### ISSUE THREAD

**Issue by Wink1992** [lloricode/e-ttendance-laravel#10]
![erroronmessage](https://user-images.githubusercontent.com/30583058/31412741-e9955730-ae48-11e7-9db4-f9ab1e2f1d60.jpg)

**Comment by Wink1992** [comment]
![erroronmessage1](https://user-images.githubusercontent.com/30583058/31413545-5757662a-ae4c-11e7-9139-4130de7dc3d1.jpg)

**Comment by lloricode** [comment]
ok ok icheck ko if vacant ako :)

**Comment by lloricode** [comment]
possible mamayang gabi ....

**Comment by lloricode** [comment]
try to visit https://github.com/musonza/chat/issues/30

**Comment by lloricode** [comment]
guys pwdi malaman dun sa error, kung anong version ang mysql nyan, yun sa error lang  related this issue.

**Comment by lloricode** [comment]
guy paki run ito sa `phpmyadmin` nyo

```
 SHOW VARIABLES LIKE "%version%";
```

dun lang sa nag error ah, para ma-solve yan

then print screen daw
