### ISSUE TITLE
Ayan na par :) hihihi

### ISSUE THREAD

**Issue by Wink1992** [lloricode/e-ttendance-laravel#2]
![issue1](https://user-images.githubusercontent.com/30583058/29012196-3bffb70a-7b6c-11e7-8e79-6f28cbeb8ce5.jpg)
![Uploading issue2.jpg…]()

**Comment by lloricode** [comment]
ok ok , wait

**Comment by lloricode** [comment]
ok pakitest daw,

**Comment by lloricode** [comment]
ok nag commit ako ng exported file.

hanapin mo yung file na nasa **root project folder**.

file: `e_ttendance_laravel.sql`

then follow this instruction na lang

[click here reference 1 ](http://www.inmotionhosting.com/support/website/phpmyadmin/import-database-using-phpmyadmin)
or
[click here reference 2 ](https://stackoverflow.com/questions/13955988/insert-sql-file-into-your-mysql-database)

**Comment by lloricode** [comment]
or ask my ex-class mate para sa importing sql file sa phpmyadmin

**Comment by Wink1992** [comment]
san ko makikita ang kioski par ?

**Comment by Wink1992** [comment]
na view ko na issue number 2 par

**Comment by Wink1992** [comment]
![issue3](https://user-images.githubusercontent.com/30583058/29013652-fb4f5aca-7b76-11e7-9ee4-82f7e5866c80.jpg)


ayan par na test ko na

**Comment by lloricode** [comment]
aw ok naman na pala? hmm so na solve na pala yung 2nd to the last na commit? without importing manual?

**Comment by lloricode** [comment]
ok means solve na :) :+1:
