### ISSUE TITLE
Par Accidentally I deleted my Xampp and I just installed it again but ,,, it appear like this

### ISSUE THREAD

**Issue by Wink1992** [lloricode/e-ttendance-laravel#3]
![nakoonaman](https://user-images.githubusercontent.com/30583058/29065666-693d77cc-7c5f-11e7-9f53-f44f31f69bc2.jpg)

**Comment by Wink1992** [comment]
par I accidentally deleted my xampp ... :(

**Comment by Wink1992** [comment]
and I reinstalled it again but it goes like what u see on the image above :(

**Comment by lloricode** [comment]
Ok na toh?

**Comment by Wink1992** [comment]
okay na par :D
