### ISSUE TITLE
Error ! on Migrating a Table on Database

### ISSUE THREAD

**Issue by Wink1992** [lloricode/e-ttendance-laravel#9]
![error2par](https://user-images.githubusercontent.com/30583058/31322189-be6c37ba-acc5-11e7-8b80-cac59a8d1c1d.jpg)
![error1par](https://user-images.githubusercontent.com/30583058/31322190-be72d926-acc5-11e7-9f91-674548cc34e7.jpg)

after Git Pull and Composer Update par ,... Nag error sia pag dating sa php artisan migrate

**Comment by Wink1992** [comment]
![error3par](https://user-images.githubusercontent.com/30583058/31322241-c036b826-acc6-11e7-807b-1f90e4b35b4c.jpg)

pag punta ko sa Admin Log in ayan nakita ko par .. Error >

**Comment by lloricode** [comment]
paki delete pala muna database nyo, then recreate lang,

**Comment by lloricode** [comment]
punta kayo sa `phpmyadmin`
then drop database
then recreate database.

tapos run nyo to
```
php artisan migrate --seed
```

**Comment by lloricode** [comment]
dont forget restart sa `serve`

re-run lang ang
```
php artisan serve
```

**Comment by lloricode** [comment]
solved ...
